name: "🧹• Cleanup workflow run history"

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: Bitte-ein-Git/action_clear-runs@main
        with:
          mode: 'repo'